language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

before_script:
    #- wget https://scrutinizer-ci.com/ocular.phar
    - composer install

script:
    - phpunit

after_script:
    #- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
