language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

before_script:
    #- composer install

    # phpcs
    pear install PHP_CodeSniffer
    phpenv rehash

script:
    - phpunit
    - phpcs
